### ISSUE TITLE
screen_width, screen_height should be options or experimental attributes, not constants

### ISSUE THREAD

**Issue by tjmahr** [tjmahr/lookr#10]

**Comment by tjmahr** [comment]
Store these constants in supplemental `yaml` files. Have Session(...) or Task(...) take a `specs` parameter which can point to a yaml path or a list enumerating these constants. The default values will use the specs for 27 inch Tobii XL60.

**Comment by tjmahr** [comment]
Here's a YAML control file might look for the Coartic experiment in `"tests/testthat/data/Coartic_WFFArea_2a/001P00XS1/"`

```yaml
---
Task: "Coartic"

Display:
  type: "Tobii60XL"
  frames_per_sec: 60.0
  screen_width: 1920
  screen_height: 1200
  pixels_per_mm: 3.71

AOIs:
  ImageL:
    x_pix: [100, 700]
    y_pix: [300, 900]
  ImageR:
    x_pix: [1220, 1820]
    y_pix: [300, 900]
...
```

Which R would parse as:
```R
> str(yaml.load_file("tests/testthat/data/Coartic_WFFArea_2a/001P00XS1/Coartic.yaml"))
List of 3
 $ Task   : chr "Coartic"
 $ Display:List of 5
  ..$ type          : chr "Tobii60XL"
  ..$ frames_per_sec: num 60
  ..$ screen_width  : int 1920
  ..$ screen_height : int 1200
  ..$ pixels_per_mm : num 3.71
 $ AOIs   :List of 2
  ..$ ImageL:List of 2
  .. ..$ x_pix: int [1:2] 100 700
  .. ..$ y_pix: int [1:2] 300 900
  ..$ ImageR:List of 2
  .. ..$ x_pix: int [1:2] 1220 1820
  .. ..$ y_pix: int [1:2] 300 900
```

**Comment by tjmahr** [comment]
Actually... rename `screen_width` to `width_pix` so that the unit is part of the key-name?

**Comment by tjmahr** [comment]
Note that in the example R code, the filename is the generic `Coartic.yaml`. I'm thinking that the file loading function will look for yaml files that are sub-strings of other experiment files. So `Coartic` dot yaml would be loaded alongside any `stimdata` or `gazedata` files that `Coartic` in their name. This will let us write very generic files to store these constants for a single experiment.

Also, why yaml? It supports comments. That's all.

**Comment by crcox** [comment]
I was actually asking myself that question "why yaml?" because I've been
using json for this sort of thing. Allowing comments is a big deal. This
makes me want to learn more about yaml.

**Comment by tjmahr** [comment]
Yeah, I've started using commented yaml files to hold constants, analysis parameters and other magic numbers for the scripts that I'm using for a paper. Plus, I think JSON has too much syntax for my collaborators.

**Comment by crcox** [comment]
I agree 100%. YAML is superior in this way and others. I just weaved it
into a project under development where I ordinarily would have used JSON
and I was rewarded immediately. It's won me over. Not that we should have
this convo on your issue thread... but YAML rocks.

**Comment by tjmahr** [comment]
Nah, it's fine. This issue threads are notes-to-self. 

FWIW, YAML is a superset of JSON. Which I think means that YAML parser can read json files.

**Comment by crcox** [comment]
Woah... if that is true, that's pretty incredible. I could implement YAML
compatibility across the board and maintain backward compatibility with my
old config generation routines. I love it.

**Comment by tjmahr** [comment]
Note that YAML 1.2 from (2009) is the superset. http://en.wikipedia.org/wiki/YAML#JSON 

But I just tried an online validator. http://nodeca.github.io/js-yaml/ Plugged some JSON on the left and it parsed.

**Comment by tjmahr** [comment]
Also, I think I've come up with a philosophy. If a human is going to write the file, YAML is preferred. It a program is outputting the file for data interchange, and if I can't use a csv file, then JSON is preferred.

**Comment by crcox** [comment]
Sounds reasonable to me. Finicky syntax is great when computers are doing
the reading and writing, and vice versa.

**Comment by tjmahr** [comment]
Nope. lookr is going into long-term maintenance mode. The next package can be more general.
