### ISSUE TITLE
weird timing thing

### ISSUE THREAD

**Issue by tjmahr** [tjmahr/lookr#23]
Today, I wondered if it would be possible to identify probable trial boundaries (Inter-Trial Intervals) from the time columns in gazedata files emitted by Eprime. 

My first thought was to `diff(gazedata$RTTime)` to calculate the difference in time between Frame N and Frame N-1. The biggest jumps in time would be the ITIs. Which works perfectly:

![image](https://cloud.githubusercontent.com/assets/1890315/13921769/862d2fae-ef47-11e5-990c-a21efa76b187.png)

But on the plot, I see some weird diffs:

![image](https://cloud.githubusercontent.com/assets/1890315/13921831/d4b6ede0-ef47-11e5-9e4e-deaf0b522a8d.png)

The first one shows up in the data as:

![image](https://cloud.githubusercontent.com/assets/1890315/13921899/28b6be02-ef48-11e5-85bb-f0b28bc2e8a6.png)

And the second as:

![image](https://cloud.githubusercontent.com/assets/1890315/13921972/6c218aa0-ef48-11e5-96a9-6fd7ec59b682.png)
## Clocks

The column `RTTime` is what we might call **Eprime Local Time**. I have used this column because stimulus presentation times in the Eprime administration log are measured with the same clock and relative time, making it easy to sync up Eprime's stimulus presentation with gaze location. RTTime is measured in milliseconds, possibly the running milliseconds from the start of the experiment:

``` r
fivenum(gazedata$RTTime)
#> [1]  27871.0  80509.0 140730.0 194358.5 248730.0
fivenum(gazedata$RTTime) / 1000
#> [1]  27.8710  80.5090 140.7300 194.3585 248.7300
fivenum(gazedata$RTTime - min(gazedata$RTTime)) / 1000
#> [1]   0.0000  52.6380 112.8590 166.4875 220.8590
```

The gazedata file also provides a column for `TETTime` for **Tobii Eye Tracker Time**, which has none of these hiccups:

![image](https://cloud.githubusercontent.com/assets/1890315/13922224/5738aadc-ef49-11e5-938d-c6e2378167c8.png)

But it's apparently measured as milliseconds since whenever computer time 0 was in the 70's

``` r
head(gazedata$TETTime)
#> [1] 1.439215e+12 1.439215e+12 1.439215e+12 1.439215e+12 1.439215e+12
#> [6] 1.439215e+12
fivenum(gazedata$TETTime - min(gazedata$TETTime))
#> [1]      0.00  52411.89 112858.95 166487.96 220861.22
fivenum(gazedata$TETTime - min(gazedata$TETTime)) / 1000
#> [1]   0.00000  52.41189 112.85895 166.48796 220.86122
```
## Questions

Some questions I need to figure out:
- Does this clock stutter happen often? Or did I just choose the one file where it happened twice?
- What does this indicate?
- Does this mean I need to synchronize time using the Tobii? 

When I synchronize time using the Tobii clock, it kinda straightens those kinks. Plots below focus on the first set of weird points...

``` r
fixed_time <- (gazedata$TETTime - min(gazedata$TETTime)) + min(gazedata$RTTime)
# Time since experiment start: Corrected vs Eprime
plot(fixed_time[2450:2700], gazedata$RTTime[2450:2700])  
```

![image](https://cloud.githubusercontent.com/assets/1890315/13923281/f1ba2b86-ef4d-11e5-9f60-6e2dc25990f4.png)

``` r
# Interframe intervals: Eprime (red) vs Tobii (black)
plot(diff(gazedata$RTTime[2450:2700]), col = "red")
points(diff(fixed_time[2450:2700]))
```

![image](https://cloud.githubusercontent.com/assets/1890315/13923361/53c0ce20-ef4e-11e5-9d7e-d603c565e6ef.png)

**Comment by zhamzham** [comment]
Hello! Thank you for bringing up this issue. I wanted to see if you could please provide some guidance. Were you able to resolve this issue? Which time did you end up using for further analysis? Thanks! Z

**Comment by tjmahr** [comment]
I used TETTime.

**Comment by tjmahr** [comment]
Ooops I think I used RTTime, but I read in both. My current code gazedata files is here https://github.com/tjmahr/littlelisteners/blob/master/R/gazedata.R

**Comment by zhamzham** [comment]
Dear Dr. Mahr,

If I understand correctly, the TobiiEyeTracker Device synchronization, when set to local, converts the timing of relevant information (pupil diameter, etc) to E-Prime time (please see attached).

For this reason, it would be correct to use the RTTime, due to the fact that the pupil size is represented by this "converted" time.

Could you please let me know if you think that is correct? Also, do you think it is a problem that TETTime and RTTime have a consistent delay (~400ms)?

Thank you again!
Kind Regards,
Zhamilya
________________________________
